# permissions for end users to view terraforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-viewer-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - terraforms/status
  verbs:
  - get
